name: clojure-layer

include:
  - ../../deps/xdg/compose.yml
  - ../../deps/clojure/compose.yml
  - ../../deps/clj-kondo/compose.yml
  - ../../deps/joker/compose.yml

services:
  clojure-layer:
    image: clojure-layer
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_CLOJURE_LAYER_PATH}
    build:
      dockerfile: Dockerfile
      tags:
        - clojure-layer
      args:
        USERNAME: ${ENV_USERNAME}
    depends_on:
      xdg:
        required: true
        condition: service_started
      clojure:
        required: true
        condition: service_started
      clj-kondo:
        required: true
        condition: service_started
      joker:
        required: true
        condition: service_started
