name: gpu-layer

include:
  - ../../deps/cuda-toolkit/compose.yml
  - ../../deps/llvm/compose.yml

services:
  gpu-layer:
    image: gpu-layer
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_CUDA_TOOLKIT_PATH}:${ENV_XDG_PATH}
      DISPLAY: $DISPLAY
    env_file:
      - ../../deps/default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - gpu-layer
    depends_on:
      cuda-toolkit:
        required: true
        condition: service_started
      llvm:
        required: true
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    stdin_open: true
    tty: true
    shm_size: 2g
    privileged: true
    volumes:
      - ${ENV_X_SERVER_VOLUME}
