services:
  xdg:
    image: xdg
    container_name: xdg
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.xdg
      tags:
        - xdg
      args:
        SPACEDOCK_XDG_HOME: ${SPACEDOCK_XDG_HOME}
        SPACEDOCK_XDG_BIN_HOME: ${SPACEDOCK_XDG_BIN_HOME}
        SPACEDOCK_XDG_CONFIG_HOME: ${SPACEDOCK_XDG_CONFIG_HOME}
        SPACEDOCK_XDG_DATA_HOME: ${SPACEDOCK_XDG_DATA_HOME}
        SPACEDOCK_XDG_CACHE_HOME: ${SPACEDOCK_XDG_CACHE_HOME}
