services:
  emacs:
    image: emacs
    container_name: emacs
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.emacs
      tags:
        - emacs
      args:
        EMACS_DIR: ${SPACEDOCK_EMACS_DIR}
        EMACS_VERSION: ${SPACEDOCK_EMACS_VERSION}
    env_file:
      - emacs.env
    depends_on:
      xdg:
        required: true
        condition: service_completed_successfully
