# template
services:

  docker-layer:
    image: docker-layer
    container_name: docker-layer
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.docker-layer
      tags:
        - docker-layer
      args:
        LAYER_NAME: docker
        LAYER_TYPE: tools
        NVM_DIR: ${SPACEDOCK_NVM_DIR}
        CABAL_DIR: ${SPACEDOCK_CABAL_DIR}
        NVM_VERSION: 0.39.3
        NODE_VERSION: 20.13.1
    depends_on:
      xdg:
        required: true
        condition: service_completed_successfully
      docker-lsp:
        required: true
        condition: service_completed_successfully
      hadolint:
        required: true
        condition: service_completed_successfully

  # ============================================================================
  # layer deps

  docker-lsp:
    image: docker-lsp
    container_name: docker-lsp
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.docker-lsp
      tags:
        - docker-lsp
      args:
        NVM_DIR: ${SPACEDOCK_NVM_DIR}
    depends_on:
      node:
        required: true
        condition: service_completed_successfully

  hadolint:
    image: hadolint
    container_name: hadolint
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.hadolint
      tags:
        - hadolint
      args:
        XDG_BIN_HOME: ${SPACEDOCK_XDG_BIN_HOME}
        XDG_CONFIG_HOME: ${SPACEDOCK_XDG_CONFIG_HOME}
        CABAL_DIR: ${SPACEDOCK_CABAL_DIR}
    depends_on:
      shellcheck:
        required: true
        condition: service_completed_successfully

  # ============================================================================
  # build deps

  node:
    image: node
    container_name: node
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.node
      tags:
        - node
      args:
        NVM_DIR: ${SPACEDOCK_NVM_DIR}
        NVM_VERSION: 0.39.3
        NODE_VERSION: 20.13.1
    depends_on:
      xdg:
        required: true
        condition: service_completed_successfully

  shellcheck:
    image: shellcheck
    container_name: shellcheck
    command: #tail -f /dev/null
    build:
      dockerfile: Dockerfile.shellcheck
      tags:
        - shellcheck
      args:
        XDG_BIN_HOME: ${SPACEDOCK_XDG_BIN_HOME}
        CABAL_DIR: ${SPACEDOCK_CABAL_DIR}
    depends_on:
      cabal:
        required: true
        condition: service_completed_successfully

  cabal:
    image: cabal
    container_name: cabal
    #command: tail -f /dev/null
    build:
      dockerfile: Dockerfile.cabal
      tags:
        - cabal
      args:
        XDG_BIN_HOME: ${SPACEDOCK_XDG_BIN_HOME}
        XDG_CONFIG_HOME: ${SPACEDOCK_XDG_CONFIG_HOME}
        XDG_DATA_HOME: ${SPACEDOCK_XDG_DATA_HOME}
        CABAL_DIR: ${SPACEDOCK_CABAL_DIR}
        BOOTSTRAP_HASKELL_NONINTERACTIVE: 1
        GHCUP_USE_XDG_DIRS: 1
        BOOTSTRAP_HASKELL_VERBOSE: 1
        BOOTSTRAP_HASKELL_ADJUST_BASHRC: 1
    depends_on:
      xdg:
        required: true
        condition: service_completed_successfully
