# syntax=docker/dockerfile:1.7-labs

################################################################################
FROM xdg AS gpu-layer
################################################################################

COPY --from=cuda / /
COPY --from=nsight-compute / /
COPY --from=llvm / /
COPY --from=mlir / /

