# syntax=docker/dockerfile:1.7-labs

# Builds dockerfile-language-server.
#
# COPY --from=docker-lsp-dep ${NVM_DIR} ${NVM_DIR}
#
# https://github.com/rcjsuen/dockerfile-language-server

ARG NVM_DIR

################################################################################
FROM node AS docker-lsp
################################################################################

ARG NVM_DIR

# ------------------------------------------------------------------------------
# install build dependencies
# ------------------------------------------------------------------------------

RUN bash -x <<"EOF"
set -eu
apt-get update
apt-get install -y --no-install-recommends \
    ca-certificates \
    git
apt-get clean
apt-get autoremove -y
rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /var/cache/*
EOF

# ------------------------------------------------------------------------------
# build dockerfile-language-server
# ------------------------------------------------------------------------------

RUN bash -x <<"EOF"
set -eu
source ${NVM_DIR}/nvm.sh
git clone https://github.com/rcjsuen/dockerfile-language-server.git
pushd dockerfile-language-server
npm install
npm audit fix
npm run build
npm test
npm install -g dockerfile-language-server-nodejs
popd
rm -rf dockerfile-language-server
EOF
