name: clojure-layer

include:
  - ../../deps/xdg/compose.yml
  - ../../deps/clojure/compose.yml
  - ../../deps/clj-kondo/compose.yml
  - ../../deps/joker/compose.yml

services:
  clojure-layer:
    image: clojure-layer
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - clojure-layer
      args:
        GOROOT: ${ENV_GO_GOROOT}
    depends_on:
      xdg:
        required: true
        condition: service_started
      clojure:
        required: true
        condition: service_started
      clj-kondo:
        required: true
        condition: service_started
      joker:
        required: true
        condition: service_started
