name: clojure-layer

include:
  - ../../deps/jdk/compose.yml

services:
  clojure-layer:
    image: clojure-layer:latest
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: layers/clojure/Dockerfile
      tags:
        - clojure-layer:latest
      args:
        JDK_VERSION: ${SPOK_JDK_VERSION}
    depends_on:
      jdk-runtime:
        required: true
        condition: service_started
