name: python

include:
  - ../xdg/compose.yml

services:
  python:
    image: python
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_PYTHON_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - python
      args:
        PYTHON_MAJOR_VERSION: ${ENV_PYTHON_MAJOR_VERSION}
        PYTHON_MINOR_VERSION: ${ENV_PYTHON_MINOR_VERSION}
        PYTHON_BUILD_NUMBER: ${ENV_PYTHON_BUILD_NUMBER}
        USERNAME: ${ENV_USERNAME}
    depends_on:
      xdg:
        required: true
        condition: service_started
