# emmy

name: emmy-runtime

include:
  - ../../deps/brave/compose.yml
  - ../../deps/gh/compose.yml
  - ../../deps/emacs/compose.yml

services:
    emmy-runtime:
      image: emmy-runtime:latest
      #command: /usr/bin/tail -f /dev/null
      environment:
        DISPLAY: $DISPLAY
        BROSWER: /usr/bin/brave-browser
        HOME: /home/${SPOK_USERNAME}
        GH_USER_NAME: ${SPOK_GH_USER_NAME}
        GH_USER_EMAIL: ${SPOK_GH_USER_EMAIL}
        XDG_CONFIG_HOME: ${SPOK_USER_XDG_CONFIG_HOME}
        SPACEMACSDIR: ${SPOK_SPACEMACSDIR}
      env_file:
        - ../default.env
        - override.env
      build:
        tags:
          - emmy-runtime:latest
        args:
          USERNAME: ${SPOK_USERNAME}
      depends_on:
        brave-runtime:
          required: true
          condition: service_started
        gh-runtime:
          required: true
          condition: service_started
        emacs-runtime:
          required: true
          condition: service_started
      stdin_open: true
      tty: true
      shm_size: 2g
      privileged: true
      volumes:
        - home:/home/${SPOK_USERNAME}
        - ${SPOK_X_SERVER_VOLUME}
volumes:
  home:
