name: clj-kondo

include:
  - ../xdg/compose.yml

services:
  clj-kondo:
    image: clj-kondo
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    environment:
      PATH: ${ENV_XDG_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - clj-kondo
    depends_on:
      xdg:
        required: true
        condition: service_started
