name: clj-kondo

include:
  - ../xdg/compose.yml

services:
  clj-kondo:
    image: clj-kondo
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - clj-kondo
    depends_on:
      xdg:
        required: true
        condition: service_started
