name: clj-kondo

include:
  - ../xdg/compose.yml

services:
  clj-kondo:
    image: clj-kondo
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_CLJ_KONDO_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - clj-kondo
      args:
        USERNAME: ${ENV_USERNAME}
    depends_on:
      xdg:
        required: true
        condition: service_started
