name: go

include:
  - ../xdg/compose.yml

services:
  go:
    image: go
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_GO_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - go
      args:
        GO_VERSION: ${ENV_GO_VERSION}
        GOROOT: ${ENV_GOROOT}
        USERNAME: ${ENV_USERNAME}
    depends_on:
      xdg:
        required: true
        condition: service_started
