name: go

include:
  - ../xdg/compose.yml

services:
  go:
    image: go
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - go
      args:
        GO_VERSION: ${ENV_GO_VERSION}
        GOROOT: ${ENV_GO_GOROOT}
    depends_on:
      xdg:
        required: true
        condition: service_started
