name: clojure

include:
  - ../xdg/compose.yml
  - ../jdk/compose.yml

services:
  clojure:
    image: clojure
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - clojure
    depends_on:
      jdk:
        required: true
        condition: service_started
