name: clojure

include:
  - ../jdk/compose.yml

services:
  clojure:
    image: clojure
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_XDG_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - clojure
    depends_on:
      jdk:
        required: true
        condition: service_started
