name: docker-layer

include:
  - ../../deps/xdg/compose.yml
  - ../../deps/hadolint/compose.yml
  - ../../deps/docker-language-server/compose.yml

services:
  docker-layer:
    image: docker-layer
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_DOCKER_LAYER_PATH}
      DISPLAY: $DISPLAY
    env_file:
      - ../../deps/default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - docker-layer
      args:
        USERNAME: ${ENV_USERNAME}
    depends_on:
      xdg:
        required: true
        condition: service_started
      hadolint:
        required: true
        condition: service_started
      docker-language-server:
        required: true
        condition: service_started
