name: bashate

include:
  - ../python/compose.yml

services:
  bashate:
    image: bashate
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_BASHATE_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - bashate
    depends_on:
      xdg:
        required: true
        condition: service_started
