name: shellcheck

include:
  - ../cabal/compose.yml

services:
  shellcheck:
    image: shellcheck
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_SHELLCHECK_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - shellcheck
      args:
        XDG_HOME: ${ENV_XDG_HOME}
        XDG_BIN_HOME: ${ENV_XDG_BIN_HOME}
        CABAL_DIR: ${ENV_CABAL_DIR}
        USERNAME: ${ENV_USERNAME}
    depends_on:
      cabal:
        required: true
        condition: service_started
