name: spok-layer

include:
  # tools
  - ../../deps/brave/compose.yml
  - ../../deps/gh/compose.yml
  - ../../deps/emacs/compose.yml
  # clojure layer
  - ../../deps/jdk/compose.yml
  - ../../deps/clojure/compose.yml
  - ../../deps/clj-kondo/compose.yml

services:
  spok-layer:
    image: spok-layer:latest
    env_file:
      - .env
    build:
      context: ../../
      dockerfile: layers/spok/Dockerfile
      tags:
        - spok-layer:latest
      args:
        EMACS_VERSION: ${SPOK_EMACS_VERSION}
    depends_on:
      # tools
      brave-runtime:
        required: true
        condition: service_started
      gh-runtime:
        required: true
        condition: service_started
      emacs-runtime:
        required: true
        condition: service_started
      # clojure layer
      jdk-runtime:
        required: true
        condition: service_started
      clojure-runtime:
        required: true
        condition: service_started
      clj-kondo-runtime:
        required: true
        condition: service_started
