name: joker

include:
  - ../xdg/compose.yml
  - ../go/compose.yml

services:
  joker:
    image: joker
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - joker
      args:
        GOROOT: ${ENV_GO_GOROOT}
    depends_on:
      go:
        required: true
        condition: service_started
