name: joker

include:
  - ../go/compose.yml

services:
  joker:
    image: joker
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_GOROOT}/bin:${ENV_XDG_PATH}
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - joker
      args:
        GOROOT: ${ENV_GOROOT}
    depends_on:
      go:
        required: true
        condition: service_started
