name: emacs

include:
  - ../deps/xdg/compose.yml

services:
  emacs:
    image: emacs
    command: ${SPACEDOCK_DEVMODE:+tail -f /dev/null}
    build:
      dockerfile: Dockerfile
      tags:
        - emacs
      args:
        EMACS_VERSION: ${EMACS_VERSION}
    depends_on:
      xdg:
        required: true
        condition: service_started
