name: cuda-toolkit

include:
  - ../xdg/compose.yml

services:
  cuda-toolkit:
    image: cuda-toolkit
    command: /usr/bin/tail -f /dev/null
    environment:
      PATH: ${ENV_CUDA_TOOLKIT_PATH}
      DISPLAY: $DISPLAY
    env_file:
      - ../default.env
      - override.env
    build:
      dockerfile: Dockerfile
      tags:
        - cuda-toolkit
      args:
        CUDA_TOOLKIT_VERSION: ${ENV_CUDA_TOOLKIT_VERSION}
        USERNAME: ${ENV_USERNAME}
        XDG_HOME: ${ENV_XDG_HOME}
    depends_on:
      xdg:
        required: true
        condition: service_started
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    stdin_open: true
    tty: true
    shm_size: 2g
    privileged: true
    volumes:
      - ${ENV_X_SERVER_VOLUME}
